name: build_and_test

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        language: [c, csharp, java, javascript]
        include:
            - os: windows-latest
              shell_script_extension: .cmd
    steps:
      - uses: actions/checkout@v3
      - run: ./${{ language}}/build_and_test${{ matrix.shell_script_extension }} | grep -q "TODO: implement test"
